package routes

import ()

var InicioRoute = "/inicio"
var ActionsRoute = "/actions"
var ClientesRoute = "/clientes"
var ConcessionariasRoute = "/concessionarias"
var ConciliacoesRoute = "/conciliacoes"
var ContratosRoute = "/contratos"
var ContratosConsumoRoute = "/contratosconsumo"
var ContratosGeracaoRoute = "/contratosgeracao"
var ContratosReparticaoRoute = "/contratosreparticao"
var CreditosRoute = "/creditos"
var FaturasConsumoRoute = "/faturasconsumo"
var FaturasGeracaoRoute = "/faturasgeracao"
var FaturasReparticaoRoute = "/faturasreparticao"
var FeaturesRoute = "/features"
var InversoresRoute = "/inversores"
var ModulosRoute = "/modulos"
var ParquesRoute = "/parques"
var ProdutosRoute = "/produtos"
var RolesRoute = "/roles"
var StatusRoute = "/status"
var UsersRoute = "/users"
var UsinasRoute = "/usinas"
var WorkflowsRoute = "/workflows"
